service: connect-snowflake-with-pandas
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: ap-northeast-1
  ecr:
    images:
      baseimage:
        path: ./docker
        file: Dockerfile
package:
  exclude:
    - docker/**
    - node_modules/**
functions:
  hello:
    image: baseimage
